//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TS24.SM24.ServerUtil.SM24Cloud {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SM24CloudWSSoapBinding", Namespace="http://service.ws.vn.com.TaxOnline/")]
    public partial class SM24CloudWS : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteTrinhKyByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListSM24TKyHDongByThangNamOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkTaiKhoanDaiLyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListSM24TaiKhoanDaiLyByFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSM24BangBaoGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateSM24TKyHDongOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSM24TrinhKyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileSM24TrinhKyHopDongOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteTaiKhoanDaiLyOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTaiKhoanDaiLyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileSM24BangBaoGiaByDaiLyOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateTaiKhoanDaiLyOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSM24TrinhKyHopDongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListSM24TrinhKyHopDongByFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListSM24TrinhKyByFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileSM24TrinhKyOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateTinhTrangSM24TrinhKyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileXacNhanSM24TrinhKyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SM24CloudWS() {
            this.Url = global::TS24.SM24.ServerUtil.Properties.Settings.Default.TS24_SM24_ServerUtil_SM24Cloud_SM24CloudWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event deleteTrinhKyByIdCompletedEventHandler deleteTrinhKyByIdCompleted;
        
        /// <remarks/>
        public event getListSM24TKyHDongByThangNamCompletedEventHandler getListSM24TKyHDongByThangNamCompleted;
        
        /// <remarks/>
        public event checkTaiKhoanDaiLyCompletedEventHandler checkTaiKhoanDaiLyCompleted;
        
        /// <remarks/>
        public event getListSM24TaiKhoanDaiLyByFilterCompletedEventHandler getListSM24TaiKhoanDaiLyByFilterCompleted;
        
        /// <remarks/>
        public event createSM24BangBaoGiaCompletedEventHandler createSM24BangBaoGiaCompleted;
        
        /// <remarks/>
        public event updateSM24TKyHDongCompletedEventHandler updateSM24TKyHDongCompleted;
        
        /// <remarks/>
        public event createSM24TrinhKyCompletedEventHandler createSM24TrinhKyCompleted;
        
        /// <remarks/>
        public event getFileSM24TrinhKyHopDongCompletedEventHandler getFileSM24TrinhKyHopDongCompleted;
        
        /// <remarks/>
        public event deleteTaiKhoanDaiLyCompletedEventHandler deleteTaiKhoanDaiLyCompleted;
        
        /// <remarks/>
        public event createTaiKhoanDaiLyCompletedEventHandler createTaiKhoanDaiLyCompleted;
        
        /// <remarks/>
        public event getFileSM24BangBaoGiaByDaiLyCompletedEventHandler getFileSM24BangBaoGiaByDaiLyCompleted;
        
        /// <remarks/>
        public event updateTaiKhoanDaiLyCompletedEventHandler updateTaiKhoanDaiLyCompleted;
        
        /// <remarks/>
        public event createSM24TrinhKyHopDongCompletedEventHandler createSM24TrinhKyHopDongCompleted;
        
        /// <remarks/>
        public event getListSM24TrinhKyHopDongByFilterCompletedEventHandler getListSM24TrinhKyHopDongByFilterCompleted;
        
        /// <remarks/>
        public event getListSM24TrinhKyByFilterCompletedEventHandler getListSM24TrinhKyByFilterCompleted;
        
        /// <remarks/>
        public event getFileSM24TrinhKyCompletedEventHandler getFileSM24TrinhKyCompleted;
        
        /// <remarks/>
        public event updateTinhTrangSM24TrinhKyCompletedEventHandler updateTinhTrangSM24TrinhKyCompleted;
        
        /// <remarks/>
        public event getFileXacNhanSM24TrinhKyCompletedEventHandler getFileXacNhanSM24TrinhKyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://factory.ws.vn.com.TaxOnline/", ResponseNamespace="http://factory.ws.vn.com.TaxOnline/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int deleteTrinhKyById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LogUser, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LogPass) {
            object[] results = this.Invoke("deleteTrinhKyById", new object[] {
                        id,
                        LogUser,
                        LogPass});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteTrinhKyByIdAsync(int id, string LogUser, string LogPass) {
            this.deleteTrinhKyByIdAsync(id, LogUser, LogPass, null);
        }
        
        /// <remarks/>
        public void deleteTrinhKyByIdAsync(int id, string LogUser, string LogPass, object userState) {
            if ((this.deleteTrinhKyByIdOperationCompleted == null)) {
                this.deleteTrinhKyByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteTrinhKyByIdOperationCompleted);
            }
            this.InvokeAsync("deleteTrinhKyById", new object[] {
                        id,
                        LogUser,
                        LogPass}, this.deleteTrinhKyByIdOperationCompleted, userState);
        }
        
        private void OndeleteTrinhKyByIdOperationCompleted(object arg) {
            if ((this.deleteTrinhKyByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteTrinhKyByIdCompleted(this, new deleteTrinhKyByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://factory.ws.vn.com.TaxOnline/", ResponseNamespace="http://factory.ws.vn.com.TaxOnline/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sm24TrinhKyHopDong[] getListSM24TKyHDongByThangNam([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tKhoanKySoTrinhKy, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tKhoanKySoKyChinh, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSche